-- 코드를 입력하세요
-- SELECT * FROM USED_GOODS_BOARD order by views desc limit 1;

SELECT CONCAT('/home/grep/src/', USED_GOODS_FILE.BOARD_ID, '/', USED_GOODS_FILE.FILE_ID, USED_GOODS_FILE.FILE_NAME, USED_GOODS_FILE.FILE_EXT) as `FILE_PATH`
FROM USED_GOODS_FILE
INNER JOIN (
    SELECT BOARD_ID from USED_GOODS_BOARD order by views desc limit 1
) as board
ON board.BOARD_ID = USED_GOODS_FILE.BOARD_ID
ORDER BY FILE_ID DESC;